### ISSUE TITLE
Error when starting the Client

### ISSUE THREAD

**Issue by snowc0de** [alexAubin/evilBunnyTrojan#2]
Can I start the server and client on the same host?

Because there is what happened (server side):

```
$ python evilBunnyServer.py
Server listening on port 8912
Connected with 127.0.0.1:50580
[127.0.0.1] Hello evil server !
Unhandled exception in thread started by <function clientHandler at 0x7f5284f061b8>
Traceback (most recent call last):
  File "evilBunnyServer.py", line 50, in clientHandler
    data = sock.recv(1024)
socket.error: [Errno 104] Connection reset by peer
```

And there is what happen (client side):

```
$ python evilBunnyTrojan.py
Segmentation fault (core dumped)
```

Can you tell me what happened?

**Comment by alexAubin** [comment]
Uh are people actually using this small dummy script I made years ago ? xD

As far as I remember, yes, I was able to run both parts on the same host ... But I do reproduce your issue (on Debian Stretch)

Not sure why that happens ... but it definitely sounds like this has to do with the client not being able to do something (maybe accessing the info from the Xorg server ?)

What distro are you running ?

**Comment by snowc0de** [comment]
I run on Ubuntu

**Comment by alexAubin** [comment]
In case you're still interested, I pushed a rework that should fix things
